### ISSUE TITLE
TimeoutError: Connection timed out after 120000ms

### ISSUE THREAD

**Issue by sergiovilar** [pgherveou/gulp-awspublish#126]
Hello,

I'm having some issues trying to upload large files (~42mb) in low internet connections:

````
/Users/sergiovilar/repos/podcast-desktop/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TimeoutError: Connection timed out after 120000ms
    at ClientRequest.<anonymous> (/Users/sergiovilar/repos/podcast-desktop/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at ClientRequest.emit (events.js:179:7)
    at TLSSocket.emitTimeout (_http_client.js:582:10)
    at TLSSocket.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket.Socket._onTimeout (net.js:324:8)
    at _runOnTimeout (timers.js:524:11)```

**Comment by sergiovilar** [comment]
Nvw, just saw the timeout option.

**Comment by ianrose** [comment]
@sergiovilar running into the same issue. You mind sharing what timeout option you used/updated that solved this?

**Comment by AboulEinein** [comment]
Same here, can you please tell us where to set the timeout option?

**Comment by AboulEinein** [comment]
Found the timeout option.
According to [AWS SDK documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) you can add `httpOptions` map and specify the `timeout` in it. 

Here's an example:

`awspublish.create({
        params: publishParams,
        accessKeyId: 'accessKeyId',
        secretAccessKey: 'secretAccessKey',
        region: 'region',
        httpOptions: {
            timeout: 300000
        }
    });`
