### ISSUE TITLE
"InvalidParameterType: Expected params.ContentType to be a string" error after updating to 3.3.2

### ISSUE THREAD

**Issue by nlaffey** [pgherveou/gulp-awspublish#150]
Our builds started failing after the package was updated to 3.3.2. Changing it back to 3.3.1 has fixed it for now. 

We aren't explicitly passing in a ContentType in either the `create` or the `publish` method options.

See the error below in our travis build:
```
/home/travis/build/TechniqueSoftware/technique-web/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

InvalidParameterType: Expected params.ContentType to be a string
    at ParamValidator.fail (/home/travis/build/TechniqueSoftware/technique-web/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/home/travis/build/TechniqueSoftware/technique-web/node_modules/aws-sdk/lib/param_validator.js:222:10)
    at ParamValidator.validateString (/home/travis/build/TechniqueSoftware/technique-web/node_modules/aws-sdk/lib/param_validator.js:154:32)
```

**Comment by pioug** [comment]
It should be fixed in latest release https://github.com/pgherveou/gulp-awspublish/releases/tag/v3.3.3.

Thanks for reporting the issue!
