### ISSUE TITLE
Call sync without calling publish first

### ISSUE THREAD

**Issue by milieu** [pgherveou/gulp-awspublish#42]
In the [docs](https://github.com/pgherveou/gulp-awspublish#publishersyncprefix) it says:
> Publisher.sync([prefix])
> create a transform stream that delete old files from the bucket. You can speficy a prefix to sync a specific directory.

In the code sample `sync()` is run after `publish()`. 

Is it possible to do the following?
```javascript
gulp.task('deploy:clean', function () {
    var publisher = awspublish.create(awskeys);
    return gulp.src(path.join(args.d, '**'))
        .pipe(publisher.sync());
});
```

Using this task results in this error for me:
```zsh
/PROJECT/node_modules/gulp-awspublish/lib/index.js:326
    newFiles[file.s3.path] = true;
                    ^
TypeError: Cannot read property 'path' of undefined
    at Transform.stream._transform (/PROJECT/node_modules/gulp-awspublish/lib/index.js:326:21)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at Transform.Writable.write (_stream_writable.js:182:11)
    at write (/PROJECT/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/PROJECT/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/PROJECT/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
```

I don't call sync after publish because I publish multiple sets of my project with different headers in separate tasks.

**Comment by pgherveou** [comment]
Not sure what you are trying to do in the first place?

Basically when you call publish each files receive some s3.* properties as described here (https://github.com/pgherveou/gulp-awspublish#publisherpublishheaders-options)
when sync is called we just list all the files that are in your bucket remove the ones that you published and deletes the one remaining 

if you dont call publish first then you dont get the extra file.s3 properties thus your error above.
Hope it clarify things a bit
