### ISSUE TITLE
UnexpectedParameter: Unexpected key 'AccessControlAllowOrigin' found in params

### ISSUE THREAD

**Issue by elado** [pgherveou/gulp-awspublish#43]
Getting `UnexpectedParameter` error when publishing with `Access-Control` extra headers. If I take them out and leave only `Cache-Control` it publishes but doesn't add the headers.

It used to work with previous versions of this module. Currently using latest of this and `aws-sdk`.

```js
var headers = {
   'Cache-Control': 'max-age=315340000, no-transform, public',
   'Access-Control-Allow-Origin': '*',
   'Access-Control-Allow-Methods': 'GET, HEAD',
   'Access-Control-Max-Age': '3000'
};


// error:

node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
MultipleValidationErrors: There were 3 validation errors:
* UnexpectedParameter: Unexpected key 'AccessControlAllowOrigin' found in params
* UnexpectedParameter: Unexpected key 'AccessControlAllowMethods' found in params
* UnexpectedParameter: Unexpected key 'AccessControlMaxAge' found in params
  at [object Object].validate (node_modules/gulp-awspublish/node_modules/aws-sdk/lib/param_validator.js:16:30)
  at Request.VALIDATE_PARAMETERS (node_modules/gulp-awspublish/node_modules/aws-sdk/lib/event_listeners.js:88:32)
```

**Comment by pgherveou** [comment]
Not sure of the details these valid parameters?
```
* UnexpectedParameter: Unexpected key 'AccessControlAllowOrigin' found in params
* UnexpectedParameter: Unexpected key 'AccessControlAllowMethods' found in params
* UnexpectedParameter: Unexpected key 'AccessControlMaxAge' found in params
```

**Comment by elado** [comment]
I think it's related to `aws-sdk` parsing, not this module.

**Comment by pgherveou** [comment]
I close it let me know if there is anything else I can do

**Comment by benjaminmcdonald** [comment]
Is not setting a custom header a limitation of this plugin or the AWS sdk?

**Comment by robwierzbowski** [comment]
I can set custom headers for `Cache-Control` with this plugin, no problem, so it's not an issue for all header values. I'm having the same issue, unable to set CORS access headers in the gulp plugin.
